Repository croct-tech/rule-engine-experiments-js, pull requests merged in 2020-05, with the labels that each got.

#2 Remove app ID from example in readme
  README.md
Labels: documentation

#3 Bump Plug and Rule Engine versions
  package-lock.json
  package.json
Labels: maintenance

#4 Use the token provided by Github for release drafts
  .github/workflows/release-drafter.yaml
Labels: maintenance

#5 Fix missing Github token
  .github/workflows/release-drafter.yaml
Labels: maintenance

#6 Fix options typing
  src/index.ts
Labels: bug

#7 Bump plug and rule engine to latest versions
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  test/index.test.ts
Labels: maintenance

#8 Import Typescript runtime
  package-lock.json
  package.json
  tsconfig.json
Labels: maintenance

#9 Bump croct/plug and croct/plug-rule-engine to the latest version
  package-lock.json
  package.json
Labels: maintenance

#10 Bump plug to version 0.3.0 and plug-rule-engine to version 0.1.0
  package-lock.json
  package.json
Labels: maintenance
